# -*- coding: utf-8 -*-
"""Q3_Partition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Jj5jWGJZZQIXUIrC5dhw8XyxCCMeX4W
"""



def partition(ll, x):
    curNode = ll.head
    ll.tail = ll.head

    while curNode:
        nextNode = curNode.next
        curNode.next = None
        if curNode.value < x:
            # Insert at the beginning
            curNode.next = ll.head
            ll.head = curNode
        else:
            # Insert at the end
            ll.tail.next = curNode
            ll.tail = curNode
        curNode = nextNode

    if ll.tail.next is not None:
        ll.tail.next = None
    # Handle case where list becomes empty or all elements moved
    if not ll.head: # If head became None, list is empty after partition
        ll.tail = None
    elif not ll.tail: # If tail became None, but head exists (e.g. all values < x)
        # Find new tail if the original tail was before new head
        temp_node = ll.head
        while temp_node.next:
            temp_node = temp_node.next
        ll.tail = temp_node


customLL = LinkedList()
customLL.generate(10,0,99)
print(customLL)
partition(customLL, 30)
print(customLL)